# Author: PaperCloud Developers
# Created on: 29/12/2023
name: Update wireguard-terraform Repository
on:
  push:
    branches:
      - main

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: papercloudtech/wireguard-terraform
          ref: main
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Setup Git
        run: |
          git config user.email "116057110+sakthisanthosh010303@users.noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Update Submodule and Push
        run: |
          git status
          git submodule update --remote
          git commit -a -m "update wireguard-terraform-aws submodule"
          git push origin main
